### ISSUE TITLE
테스트 서버 오류 관련

### ISSUE THREAD

**Issue by trollering12312** [BC-MOA/MOA-FE#21]
## 이슈 내용

`npm run start` 실행시 오류가 발생하는 문제

## 상세 내용

![image](https://user-images.githubusercontent.com/71876877/150831838-aeeb4fd4-0152-4afb-8529-3586ebd90bab.png)

오류 내용은 위 이미지와 같음
<br>

`package.json`의 proxy 관련 내용을 삭제하니 `npm run start`을 오류 없이 실행 가능했지만 API 사용을 위해서 해결해야함

## 시도해본 해결법

1) ~~`node_modules` 디렉토리 삭제 후 `npm i`실행~~
2) ~~`package.json`에 설정을 추가~~
3) 명령어에 다른 옵션을 추가해봄(해결!!!)

> https://github.com/facebook/create-react-app/issues/11762
https://create-react-app.dev/docs/advanced-configuration/

명령어를 다음과 같이 수정했더니 해결되었습니다

` "start": "cross-env HOST=localhost DANGEROUSLY_DISABLE_HOST_CHECK=true NODE_PATH=src react-scripts start",
`
## Todo

- [x] 위 옵션이 의미하는 바를 파악하기
- [x] 다른 사람의 작업 환경에서도 테스트하기

**Comment by 0andme** [comment]
음 api 관련해서 프록시 설정말고는 추가된 내용이 없어서...
start 스크립트 인식을 못하는거 보니까 cross-env 패키지 설치가 필요해서 저런 오류가 처음에 나온 것 같고...
혹시 여전히 오류가 나고 계신가요? yarn start 해보셨을까요?

**Comment by 0andme** [comment]
현재 제 로컬에서 npm run start / yarn start 둘다 로컬서버 실행에는 문제가 없는 것으로 보여집니다😥

**Comment by trollering12312** [comment]
`proxy~ `된 부분을 지웠더니 지금은 작동하고 있어요!

그 설정을 지워도 상관 없는지 궁금해서요

**Comment by 0andme** [comment]
나중에 저희 api 연결하기 위해서는 필요한 부분이라..해결되어야 할 것 같아요

**Comment by trollering12312** [comment]
정확히는 `"proxy": "http://localhost:8080"` 이 문구인데

지웠을 때는 동작하고, 있으면 명령어가 동작을 안하네요

**Comment by trollering12312** [comment]
일단 지우면서 진행하고 멘토님 트러블 슈팅 시간에 여쭤봐도 괜찮을 것 같습니다

BE 테스트 하실때 추가로 설정하신거 있으면 알려주세요

**Comment by 0andme** [comment]
크로스 env 설치 / 프록시 설정 /  axios 패키지 설치 / jsconfig.json 추가 및 코드 작성 / 가 설정한 것들이에요 
넵 오늘 트러블 슈팅 시간 같이 정하면 좋을 것 같네요!👍
