### ISSUE TITLE
챌린지 페이지 API 관련

### ISSUE THREAD

**Issue by trollering12312** [BC-MOA/MOA-FE#40]
## 이슈 내용

챌린지 컴포넌트 관련 문서/API관련 논의

**컴포넌트리스트**
[일반 컴포넌트](#normal)
[카드 컴포넌트](#card)
[함수](#func)
[컴포넌트 맵](#map)

**API 논의**
[API 관련](#api)

<br>
<br>
<br>

## 컴포넌트 리스트
<a name="normal"/>

### 일반 컴포넌트

* Header

페이지 상단의 헤더

위치 : `src\components\common\Header.js`
props
> title : bool | true면 제목 활성화
> keys : num | 키 개수 설정, 천개부터 k 표기법으로 전환됨
> alarm : bool | true면 알람 아이콘 활성화

* Banner

이미지 형태의 링크

위치 : `src\components\compete\comp\Banner.js`
props
>to : string | 관련 링크
> src : string | 이미지 url

* BannerSwiper

`Swiper`라이브러리를 활용한 배너 swiper

위치 : `src\components\compete\comp\BannerSwiper.js`
props
> 없음, 컴포넌트 스타일을 통해 크기 조절 가능

* StyledBetButtonBox, StyledBetButton

내 챌린지 참여중 카드의 버튼 디자인을 위한 컴포넌트

위치 : `src\components\compete\comp\BetCardButton.js`
props
> 없음

* PercentBar

챌린지 상세 페이지에서 걸린 비율을 보여주는 컴포넌트

위치 : `src\components\compete\comp\PercentBar.js`
props
> totalkey : list | 대상별로 걸린 키의 개수를 가지는 list 
>`[12, 37]`

* PopUp

위치 : `C:\Users\Trollering\Desktop\projects\MOA-FE\client\src\components\compete\comp\PopUp.js`
props
>onclick : function | `BetCompCard`에 사용된 state를 toggle 시켜주는 함수
> title : string | 챌린지 제목

<a name="card"/>

### 카드 컴포넌트

카드에는 다양한 컴포넌트들이 블럭처럼 조립되어있습니다
이 중에서 대표적인 요소들을 설명합니다

* BasicCompCard

챌린지 개요를 보여주는 카드

위치 : `src\components\compete\comp\Card.js`
props
> key: string | 데이터키
> obj
``` js
{
      key: "A1", //데이터키
      due: new Date("2022-01-14T21:00:00"),//마감 날짜 string or 객체
      thumb: "music.png", //이미지 url
      title: "오늘 뮤직뱅크 1위는?", // 챌린지 제목
      versus: ["아이유", "BTS"], //챌린지 대상
      total: 100, // 참여한 인원수
 }
```

* BetCompCard

내가 참여중인 만료전 챌린지를 보여주는 카드

위치 : `src\components\compete\comp\Card.js`
props
> key: string | 데이터키
> obj
``` js
{
     //BasicCompCard와 동일한 데이터

     //추가 데이터
      bet: 3, // 베팅한 열쇠 개수(1~5)
      pick: true, // 내가 고른 챌린지 대상 | true면 왼쪽, false면 오른쪽
 }
```

* BetEndCompCard

위치 : `src\components\compete\comp\Card.js`
props
> key: string | 데이터키
> type: bool | 전체/내 챌린지 구분을 위해
> obj
``` js
{
      key: "A1", //데이터키
      thumb: "music.png", //이미지 url
      title: "오늘 뮤직뱅크 1위는?", // 챌린지 제목
      versus: ["아이유", "BTS"], //챌린지 대상

      //추가 데이터
      win: true, // 승리한 챌린지 대상 | true면 왼쪽, false면 오른쪽
 }
```
<a name="func"/>

### 함수들

* formatDate

위치 : `src\components\compete\comp\DateChanger.js`

날씨 객체를 받아 적당한 형식으로 변경해줌
`1.28 (금) 21:00 마감`

* kFormatter

위치 : `src\components\compete\comp\kFormatter.js`

자리수가 초과되는 숫자를 k 표기법으로 변경해줍니다
`3000 -> 3k`

* SetType, Type

`Type`은 button이 스타일된 컴포넌트
`disabled`와 state를 변경하는 `onClick` 속성 설정이 필요함

위치 : `src\components\compete\comp\SetCategory.js`
props
> 없음

<a name="map"/>

### 컴포넌트맵

페이지 단위의 컴포넌트들이나 거기에 포함되는 커다란 컴포넌트를 정리했습니다

https://www.gloomaps.com/RPz2mtlTcf)](https://www.gloomaps.com/RPz2mtlTcf

<a name="api"/>

## API관련 

shorturl.at/kpIM6

### 테스트를 위해 사용한 데이터 객체 예시

* 전체 챌린지 리스트
``` js
{
      key: "A1",
      due: new Date("2022-01-14T21:00:00"),
      thumb: "music.png",
      title: "오늘 뮤직뱅크 1위는?",
      versus: ["아이유", "BTS"],
      totalkey: [13, 29],
      total: 100,
      win: true,
}
```

* 사용자 참여 챌린지 리스트
```js
{
    key: "B1",
    due: new Date("2022-01-14T21:00:00"),
    thumb: "music.png",
    title: "오늘 뮤직뱅크 1위는?",
    versus: ["아이유", "BTS"],
    totalkey: [13, 29],
    total: 100,
    bet: 3,
    pick: true,
    win: true,
},
```

### 데이터 타입 관련

- [x] 데이터 키가 있는지? - 자동으로 할당됨
- [x] 테이블간에 곂치지는 않는가? - 안 곂침
- [x] 데이터 키의 타입은? -  integer
- [x] 이미지 저장 type은?  - png
- [x] 날짜 데이터 저장 type은? - string

### 데이터 구성 관련

- [x] 일반 리스트/사용자리스트를 서로 분리할건지? - 분리는 함
- [x] 사용자 참여 리스트에도 챌린지 정보를 내장할 것인지/중복되는데이터-key값으로 접근하도록

### 실시간 데이터 관련

실시간 데이터부분은 API를 주기적으로 호출하는 방식을 사용할 것 같습니다 - `react-query`같은...

BE측에서 무언가 설정하실 건 없지만, 위 방식이 API를 일정한 주기로 호출하게되는데 그럴경우 서버에 부담이 될 것같아서
논의할 점이 있을것 같습니다

- [x] API 호출시 부담이 되지 않는 주기는? - 테스트 필요(사용자 1명으로 가정하고)
- [x] 필요한 데이터값만 불러오는 별도의 API를 생성할 수 있는지? 챌린지 정체 정보가 아닌 특정 속성 값만 - 설계 관점에서 좋은 방식은 아니다

**Comment by ShadowOfShadow** [comment]
고생하셨습니다!!
